# Generated by Django 4.2.18 on 2025-02-16 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
