# Generated by Django 4.2.18 on 2025-02-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signup", "0002_alter_student_name_alter_student_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
